CREATE TABLE `approval_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quotationId` int NOT NULL,
	`requestType` enum('discount','free_item','price_override','final_approval') NOT NULL,
	`requestedBy` varchar(128) NOT NULL,
	`requestedValue` text,
	`reason` text,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewedBy` varchar(128),
	`reviewNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	CONSTRAINT `approval_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `media_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`playbookItemId` int,
	`itemKey` varchar(128),
	`nameAr` varchar(255) NOT NULL,
	`fileType` enum('image','video','render','document') NOT NULL,
	`fileUrl` text NOT NULL,
	`thumbnailUrl` text,
	`usageType` enum('client_presentation','training','objection_handling','showroom') NOT NULL,
	`script` text,
	`priorityLevel` int DEFAULT 1,
	`tags` varchar(512),
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `media_library_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `playbook_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`itemKey` varchar(128) NOT NULL,
	`itemNameAr` varchar(255) NOT NULL,
	`itemNameEn` varchar(255),
	`category` enum('material','accessory','cladding','marble','transport','labor') NOT NULL,
	`technicalDescription` text,
	`salesExplanation` text,
	`whenToRecommend` text,
	`whenNotToRecommend` text,
	`commonObjections` text,
	`objectionAnswers` text,
	`cheaperAlternativeId` int,
	`premiumAlternativeId` int,
	`tags` varchar(512),
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `playbook_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `playbook_items_itemKey_unique` UNIQUE(`itemKey`)
);
--> statement-breakpoint
CREATE TABLE `quotations_v2` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quotationCode` varchar(32) NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`parentQuotationId` int,
	`clientName` varchar(128),
	`clientPhone` varchar(32),
	`address` text,
	`governorate` varchar(64),
	`projectCode` varchar(64),
	`engineerName` varchar(128),
	`engineerRole` enum('sales_engineer','designer','technical_office','sales_manager','admin','owner') DEFAULT 'sales_engineer',
	`kitchenLength` varchar(16),
	`kitchenWidth` varchar(16),
	`totalUnits` int DEFAULT 0,
	`lowerUnitsArea` varchar(16),
	`upperUnitsArea` varchar(16),
	`tallUnitsArea` varchar(16),
	`specialUnitsArea` varchar(16),
	`materialsJson` text,
	`accessoriesJson` text,
	`claddingJson` text,
	`marbleJson` text,
	`transportJson` text,
	`discountType` enum('none','percentage','fixed') DEFAULT 'none',
	`discountValue` int DEFAULT 0,
	`discountReason` text,
	`discountApprovedBy` varchar(128),
	`materialsTotalPrice` int DEFAULT 0,
	`accessoriesTotalPrice` int DEFAULT 0,
	`claddingTotalPrice` int DEFAULT 0,
	`marbleTotalPrice` int DEFAULT 0,
	`transportTotalPrice` int DEFAULT 0,
	`subtotal` int DEFAULT 0,
	`discountAmount` int DEFAULT 0,
	`grandTotal` int DEFAULT 0,
	`warningsJson` text,
	`status` enum('draft','pending_approval','approved','sent_to_client','accepted','rejected','revised') NOT NULL DEFAULT 'draft',
	`approvalStatus` enum('not_required','pending','approved','rejected') DEFAULT 'not_required',
	`approvedBy` varchar(128),
	`approvedAt` timestamp,
	`lockedAt` timestamp,
	`notes` text,
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_v2_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotations_v2_quotationCode_unique` UNIQUE(`quotationCode`)
);
--> statement-breakpoint
CREATE TABLE `sales_scripts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`itemKey` varchar(128) NOT NULL,
	`shortClientExplanation` text,
	`premiumExplanation` text,
	`objectionResponse` text,
	`whatsappFollowUp` text,
	`showroomPresentationLine` text,
	`language` enum('ar','en') NOT NULL DEFAULT 'ar',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sales_scripts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transport_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`governorate` varchar(128) NOT NULL,
	`basePrice` int NOT NULL,
	`pricePerKm` int DEFAULT 0,
	`carryingPrice` int DEFAULT 0,
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `transport_rules_id` PRIMARY KEY(`id`)
);
